name: Build and Test Swaglabs 

on: 
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t playwright-tests .

      - name: Run tests in container
        run: docker run --rm -v ${{ github.workspace }}/reports:/app/reports playwright-tests

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: reports/
      
