name: Build and Test Swaglabs 

on: 
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache
        uses: actions/cache@v5.0.5
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          playwright install --with-deps chromium

      - name: Run tests 
        run: pytest saucedemo/tests --html=report.html

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with: 
          name: test-report
          path: report.html
      - name: Run Hello World
        run: echo Hello World
      
